; PlatformIO Project Configuration File
; CDC Badge OS

[platformio]
src_dir = main

[env:cdc_badge_usb]
platform = espressif32@6.12.0
board = cdc-badge-usb
framework = espidf
board_build.partitions = partitions.csv
board_build.flash_size = 16MB
board_build.psram = enabled
board_build.sdkconfig_defaults = sdkconfig.defaults
platform_packages =
    framework-espidf @ ~3.50500.0
    toolchain-xtensa-esp32s3 @ 12.2.0+20230208
build_flags =
    -std=gnu++17
    -D BUILD_TIME=__TIME__
    -D BUILD_DATE=__DATE__
    -D APP_NAME=\"CDCBos\"
    -D APP_VERSION=\"0.6.2\"
    ; TinyUSB configuration
    -D CONFIG_TINYUSB_ENABLED=1
    -D CONFIG_TINYUSB_CDC_ENABLED=1
    -D CONFIG_TINYUSB_CDC_RX_BUFSIZE=256
    -D CONFIG_TINYUSB_CDC_TX_BUFSIZE=256
    ; libtropic helpers
    -DLT_HELPERS
lib_deps =

build_unflags =
    -std=gnu++2b
    -std=gnu++23

extra_scripts =
    pre:tools/pio_python_deps.py
    pre:tools/pio_submodules.py
    pre:tools/pio_component_manager.py

#upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1020BA59B7481
monitor_speed = 115200
